### ISSUE TITLE
Improve PAM resource matching ability

### ISSUE THREAD

**Issue by samcornwell** [simp/inspec-profile-disa_stig-el7#19]
The new PAM resource is a bit limited in the ability to match parameters against a range of numerical values (for example). A regular expression is required. One solution to this would be if PAM resource could match values using native matchers.

**Comment by trevor-vaughan** [comment]
@samcornwell Could you provide an example of this where the arguments are known? One of the reasons that I didn't go down this route was that you would need to know exactly what you are looking at. Or are you suggesting that, should we have a number, we try numeric matches and fall back to a regex if that raises an exception?

**Comment by samcornwell** [comment]
fixed by #41
