### ISSUE TITLE
Tests should be wrapped in conditional to check whether it failed due to lack of permissions

### ISSUE THREAD

**Issue by frezbo** [simp/inspec-profile-disa_stig-el7#2]
Running inspec without **sudo** might fail some of the tests, the tests should be wrapped in a conditional to check for the superuser privilege.

**Comment by trevor-vaughan** [comment]
@frezbo What do you think about making this something built into InSpec itself? A `sudo_required` tag or something? Then, things can fail fast.

**Comment by frezbo** [comment]
Better :D

**Comment by trevor-vaughan** [comment]
@frezbo Filed an upstream ticket at https://github.com/chef/inspec/issues/2300
