### ISSUE TITLE
Consider Updating mfa_package_list Defaults

### ISSUE THREAD

**Issue by Bialogs** [simp/inspec-profile-disa_stig-el7#57]
I was doing a bit of investigating on RHEL's MFA/Smartcard requirements and they posted [this](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system-level_authentication_guide/smartcards). The control currently has the STIG recommended check of three packages: 
```yaml
mfa_pkg_list: [
    'esc',
    'pam_pkcs11',
    'authconfig-gtk',
]
```

If you want to consider the RHEL documentation `mfa_pkg_list` would look something like 

```yaml
mfa_pkg_list: [
    'nss-tools',
    'nss-pam-ldapd',
    'esc',
    'pam_pkcs11',
    'pam_krb5',
    'opensc',
    'pcsc-lite-ccid',
    'gdm',
    'authconfig',
    'authconfig-gtk',
    'krb5-libs',
    'krb5-workstation',
    'krb5-pkinit',
    'pcsc-lite',
    'pcsc-lite-libs'
]
```

**Comment by trevor-vaughan** [comment]
The RHEL docs should be considered authoritative in my opinion.
