### ISSUE TITLE
V-71941 could return a false pass

### ISSUE THREAD

**Issue by rx294** [simp/inspec-profile-disa_stig-el7#93]
The test with current design will return a **false pass** when INACTIVE is set to **default** value `-1`
which **disables** feature

https://github.com/simp/inspec-profile-disa_stig-el7/blob/ecdf03ee922373c486286c5cfe67ef608bae874f/controls/V-71941.rb#L46

A check should be added to verify that `INACTIVE >= 0`

**Comment by aaronlippold** [comment]
@djhaynes can you open a PR for this

**Comment by aaronlippold** [comment]
@rx294 can you ask Danny or could you open a PR for this
